### ISSUE TITLE
GBA Configuration

### ISSUE THREAD

**Issue by HereInPlainSight** [ProfessorKaos64/Ice#4]
Hi!  I've actually had an issue with GBA play through Ice here, and I think I found the issue in that in consoles.txt you have:
```
[Nintendo Gameboy Advance]
nickname=GBA
emulator=RetroArch_GB
```
Seems to work fine after modding the last line to be
`emulator=RetroArch_GBA`
to match emulators.txt

Of note I noticed the filter 'Nintendo Gameboy Advance' gets cut off into 'Nintendo Gameboy' (for me at least).  Not sure if that's something you want to address.  On a personal note you may want to mention that the config files live in /etc/ice/ .  Maybe I was oblivious not to just check in /etc/ right away, but it was helpful to have found them!  <.<

Incidentally, I doubt this has anything to do with your repo whatsoever, but just to mention I had to add the steam user to the input group to get access to controllers in PCSX2.  I have not seen mention of that anywhere at all, so I'm not sure if that's something unusual in my specific system or not, or something in SteamOS, but figured I'd mention it since I grabbed it from your repo.

**Comment by ProfessorKaos64** [comment]
Fixed, thank you. I'll check out the filter. This would require switching up the folder/naming conventions, but I can certainly do that. I'll shorten then in the next ice-unstable. I am trying to work out some issues with a few other packages at the moment. I'll add a note to the wiki on SteamOS-Tools for ice about PCSX2, thanks!

**Comment by ProfessorKaos64** [comment]
I should note, and possibly take down this repo, as the packaging files don't live here. I merely supplement the config.txt files etc. with the standard repo from Scott Rice (to keep away from maintaining with upstream).
